name: y-store

services:
  backend:
    image: node:18-alpine
    container_name: y-store-backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && node server.js"
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    ports:
      - target: 3000
        published: ${WEBUI_PORT}
        protocol: tcp
    restart: unless-stopped
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Timezone environment variable
        - container: PUID
          description:
            en_US: User ID to run the container as
        - container: PGID
          description:
            en_US: Group ID to run the container as
      ports:
        - container: "3000"
          description:
            en_US: Backend API port

  frontend:
    image: nginx:stable-alpine
    container_name: y-store-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - target: 80
        published: 8080
        protocol: tcp
    restart: unless-stopped
    x-casaos:
      ports:
        - container: "80"
          description:
            en_US: Frontend webserver port

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: backend
  author: Yaman
  category: AppStore
  description:
    en_US: "Custom CasaOS App Store frontend and backend proxy."
  developer: Yaman
  icon: https://export-download.canva.com/2tHw4/DAGrW92tHw4/7/0/0001-3681039969238197907.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAQYCGKMUH5AO7UJ26%2F20250726%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250726T231122Z&X-Amz-Expires=40792&X-Amz-Signature=f017bf9d34105d5fa1a95b34f2671b8b9326beee6fa7a8c908c5a9f0b6ccb3df&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27YTV%2520Apps.png&response-expires=Sun%2C%2027%20Jul%202025%2010%3A31%3A14%20GMT
  tagline:
    en_US: "An alternative app store for CasaOS."
  title:
    en_US: "Y-Store"
  index: /
  port_map: ${WEBUI_PORT}
